apiVersion: v1
kind: Service
metadata:
  name: svc-tekever-challenge
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-2:456940189458:certificate/a66f0e24-210f-4a94-b10f-0409a4365e26
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      nodePort: 30002
  selector:
    app: tekever-challenge
# type: NodePort
# ports:
#   - port: 5000
#     nodePort: 32022
# selector:
#   app: tekever-challenge
